variables:
  # These are gitlab variables so that it's easier to do a manual deploy
  # If these are set witih value and description, then it gives you UI elements
  DOWNSTREAM_BRANCH:
    value: "libddprof-v0.5.0-rc.1"
    description: "Run a specific branch downstream"

trigger_internal_build:
  variables:
    DD_PROF_PHP_COMMIT_BRANCH: $CI_COMMIT_BRANCH
    DD_PROF_PHP_COMMIT_SHA: $CI_COMMIT_SHA
    DD_PROF_PHP_SHORT_COMMIT_SHA: ${CI_COMMIT_SHORT_SHA}
  trigger:
    project: DataDog/dd-prof-php-build
    strategy: depend
    branch: $DOWNSTREAM_BRANCH
