version: 2.1

jobs:

  build:
    docker:
      - image: cimg/base:2022.01
    steps:
      - checkout
      - run:
          name: What does the directory layout look like?
          command: |
            pwd
            ls -lh .

#      - run:
#          name: Add OS packages
#          command: |
#            set -euo pipefail
#            user=$(whoami)
#            sudo apt-get update
#            sudo apt-get install -y php7.4-dev libuv1-dev
#
#      - run:
#          name: Add /opt packages
#          command: |
#            curl -OL https://github.com/DataDog/libddprof/releases/download/v0.2.0/libddprof-x86_64-unknown-linux-gnu.tar.gz
#            sha256sum="cba0f24074d44781d7252b912faff50d330957e84a8f40a172a8138e81001f27"
#            echo "$sha256sum  libddprof-x86_64-unknown-linux-gnu.tar.gz" | sha256sum -c
#            export DDProf_ROOT="/opt/libddprof"
#            sudo mkdir -p "$DDProf_ROOT"
#            sudo chown "$user" "$DDProf_ROOT"
#            tar -x --strip-components 1 \
#              -f libddprof-x86_64-unknown-linux-gnu.tar.gz \
#              -C "$DDProf_ROOT"
#            curl -OL https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.tar.gz
#            sha256sum="73565c72355c6652e9db149249af36bcab44d9d478c5546fd926e69ad6b43640"
#            echo "$sha256sum  cmake-3.22.1-linux-x86_64.tar.gz"
#            sudo mkdir -p /opt/cmake
#            sudo chown $user /opt/cmake
#            tar -x --strip-components 1 \
#              -f cmake-3.22.1-linux-x86_64.tar.gz \
#              -C /opt/cmake
#            PATH="/opt/cmake/bin:$PATH"
#
#      - run:
#          name: Build PHP profiling
#          command: |
#            pwd #where does checkout go?
